- 根据之前的反馈建议进行优化
chronolaw/cpp_study pull request #7
Opened 2020-05-09 05:45 UTC by xiaomiwujiecao

- macos section0/test.cpp 使用 #ifdef 宏 进行了判断
- 优化了CmakeLists.txt,增加section1的Cmake文件

2020-05-11 10:45 UTC, xiaomiwujiecao commented
现在可以合并了吗

2020-05-13 09:24 UTC, chronolaw requested changes
需要解决#ifdef的格式问题才可以合并，可以参考预处理那一讲。

2020-05-13 09:24 UTC, chronolaw commented on section0/test.cpp
> +    #ifdef __GLIBCXX__
条件编译应该顶格，不参与C++语法的缩进

2020-05-23 06:33 UTC, xiaomiwujiecao commented
优化第一章 #ifdef 宏定义的代码格式
- 添加各章节 CmakeLists.txt, 增加 json.hpp 头文件依赖

2020-05-23 06:33 UTC, xiaomiwujiecao commented on section0/test.cpp
> +    #ifdef __GLIBCXX__
优化第一章 #ifdef 宏定义的代码格式
- 添加各章节 CmakeLists.txt, 增加 json.hpp 头文件依赖

2020-05-23 07:00 UTC, xiaomiwujiecao commented
合并最新源码

2020-05-23 11:05 UTC, merged